(() => {
  document.querySelectorAll('[data-framer-hydrate-v2],[data-framer-ssr-released-at],[data-framer-page-optimized-at]').forEach((node) => {
    node.removeAttribute('data-framer-hydrate-v2');
    node.removeAttribute('data-framer-ssr-released-at');
    node.removeAttribute('data-framer-page-optimized-at');
  });
  const links={autos:'https://www.instagram.com/rodricgt3/',personal:'https://www.instagram.com/rodricgrs/',tiktok:'https://www.tiktok.com/@rodricgt3',email:'mailto:glzcales@gmail.com'};
  const replace=(a,b)=>document.querySelectorAll('*').forEach(n=>{if(!n.children.length&&n.textContent?.includes(a))n.textContent=n.textContent.replaceAll(a,b)});
  replace('Linker','Rodric GT3');replace('Justin Farrugia','Rodric GT3');replace('Justin','Rodric');replace('@justinmfarrugia','@rodricgt3');document.title='Rodric GT3 — Autos, carspotting y proyectos';
  document.querySelector('meta[name="description"]')?.setAttribute('content','Rodric GT3: autos, carspotting, eventos y proyectos digitales.');
  document.querySelectorAll('a[href*="instagram.com"],a[href*="twitter.com"]').forEach((a,i)=>{a.href=i%2?links.personal:links.autos;a.target='_blank';a.rel='noopener noreferrer'});document.querySelectorAll('a[href*="tiktok.com"]').forEach(a=>{a.href=links.tiktok;a.target='_blank';a.rel='noopener noreferrer'});
  const section=document.createElement('section');section.className='rodric-contact-projects';section.innerHTML=`<div class="rodric-panel"><p class="rodric-eyebrow">Trabajemos juntos</p><h2>Proyectos, sitios y experiencias para el mundo automotriz.</h2><p>¿Tienes una marca, evento o idea? Hablemos.</p><a class="rodric-email" href="${links.email}">glzcales@gmail.com <span>↗</span></a></div><div class="rodric-panel"><p class="rodric-eyebrow">Mis proyectos</p><div class="rodric-projects"><a href="${links.autos}" target="_blank">Rodric GT3 <small>Autos · Instagram ↗</small></a><a href="${links.personal}" target="_blank">Rodric personal <small>Instagram ↗</small></a><a href="${links.tiktok}" target="_blank">Rodric GT3 <small>TikTok · Autos ↗</small></a></div></div>`;document.body.append(section);
  const style=document.createElement('style');style.textContent=`.rodric-contact-projects{width:min(900px,calc(100% - 32px));margin:36px auto 80px;display:grid;grid-template-columns:1.1fr .9fr;gap:14px;color:#f5f5f5;font-family:Inter,system-ui,sans-serif}.rodric-panel{padding:24px;border:1px solid #fff2;border-radius:24px;background:#fff1;backdrop-filter:blur(12px)}.rodric-eyebrow{margin:0 0 10px;color:#aaa;font-size:12px;text-transform:uppercase;letter-spacing:.12em}.rodric-panel h2{margin:0 0 10px;font-size:clamp(22px,4vw,38px);line-height:1.06;letter-spacing:-.04em}.rodric-panel p:not(.rodric-eyebrow){color:#aaa;line-height:1.5}.rodric-email{display:inline-flex;gap:10px;margin-top:10px;padding:12px 16px;border-radius:999px;background:#fff;color:#111;text-decoration:none;font-weight:600}.rodric-projects{display:grid;gap:10px}.rodric-projects a{display:flex;justify-content:space-between;gap:12px;padding:15px 16px;border:1px solid #fff2;border-radius:16px;color:#fff;text-decoration:none}.rodric-projects small{color:#aaa}@media(max-width:700px){.rodric-contact-projects{grid-template-columns:1fr;width:calc(100% - 24px)}.rodric-projects a{flex-direction:column;gap:4px}}`;document.head.append(style);
})();
